"""Built-in insight rules package."""

from app.insights.rules.assets import (
    BestAssetRule,
    BestMonthRule,
    BestYearRule,
    GoalProgressRule,
    GoalTrackingStubRule,
    LosingAssetsCountRule,
    PopularAssetRule,
    StagnantAssetRule,
    WellDiversifiedRule,
    WorstAssetRule,
    WorstMonthRule,
    WorstYearRule,
)
from app.insights.rules.base import InsightRule
from app.insights.rules.behavior import (
    ConsecutiveLossMonthsRule,
    IdleCapitalRule,
    InactivePortfolioRule,
    LongHoldingLossRule,
    OverTradingRule,
    ShortTermWinsRule,
    TooManySmallTradesRule,
    UnderTradingRule,
)
from app.insights.rules.performance import (
    FeeWarningRule,
    HighFeeRatioRule,
    HighUnrealizedLossRule,
    HighWinRateRule,
    LargestLoserRule,
    LargestWinnerRule,
    LowProfitFactorRule,
    LowWinRateRule,
    NegativeExpectancyRule,
    NegativeRoiRule,
    PortfolioDeclineRule,
    PortfolioGrowthRule,
    PositiveRoiRule,
    WeakRecoveryFactorRule,
)
from app.insights.rules.risk import (
    HighExposureRule,
    HoldingConcentrationRule,
    LargeAllocationRule,
    LargeDrawdownRule,
    LossConcentrationRule,
    NoDiversificationRule,
    ProfitConcentrationRule,
    SingleAssetRiskRule,
)

DEFAULT_RULES: list[InsightRule] = [
    LargeAllocationRule(),
    SingleAssetRiskRule(),
    NoDiversificationRule(),
    HoldingConcentrationRule(),
    ProfitConcentrationRule(),
    LargeDrawdownRule(),
    HighExposureRule(),
    LossConcentrationRule(),
    NegativeRoiRule(),
    PositiveRoiRule(),
    LowWinRateRule(),
    HighWinRateRule(),
    LowProfitFactorRule(),
    NegativeExpectancyRule(),
    WeakRecoveryFactorRule(),
    HighFeeRatioRule(),
    FeeWarningRule(),
    LargestWinnerRule(),
    LargestLoserRule(),
    PortfolioGrowthRule(),
    PortfolioDeclineRule(),
    HighUnrealizedLossRule(),
    TooManySmallTradesRule(),
    OverTradingRule(),
    UnderTradingRule(),
    InactivePortfolioRule(),
    LongHoldingLossRule(),
    ShortTermWinsRule(),
    ConsecutiveLossMonthsRule(),
    IdleCapitalRule(),
    BestAssetRule(),
    WorstAssetRule(),
    PopularAssetRule(),
    StagnantAssetRule(),
    LosingAssetsCountRule(),
    BestMonthRule(),
    WorstMonthRule(),
    BestYearRule(),
    WorstYearRule(),
    WellDiversifiedRule(),
    GoalTrackingStubRule(),
    GoalProgressRule(),
]

__all__ = ["InsightRule", "DEFAULT_RULES"]
